### ISSUE TITLE
Unhandled exception using any model

### ISSUE THREAD

**Issue by Nighthawk1207** [TiredHobgoblin/Destiny-Collada-Generator#20]
While attempting to rip any model from the API getting this error after about a minute of no activity:
(Hash at the time of writing this issue was: `2899766705`

```DCG(stderr): Unhandled exception.
DCG(stderr): System.AggregateException: One or more errors occurred. (A task was canceled.)
---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at System.Threading.Tasks.Task`1.get_Result()
at DestinyColladaGenerator.ApiSupport.MakeCallJson(String url) in ./ApiSupport.cs:line 49
at DestinyColladaGenerator.ApiSupport.UpdateLocalManifest() in ./ApiSupport.cs:line 191
at DestinyColladaGenerator.ApiSupport.convertByHash(String game, String[] hashes, String fileOut) in ./ApiSupport.cs:line 262
at DestinyColladaGenerator.Program.Main(String[] args) in ./Program.cs:line 97

DCG exited with code 3762504530

**Comment by TiredHobgoblin** [comment]
That looks like a failure to make a network connection. Can you please confirm you’re using the latest version of the tool?

**Comment by Nighthawk1207** [comment]
I am using the newest release of the tool v1.7.13

**Comment by Nighthawk1207** [comment]
Hm. I tried running it once more today and it seems to be working fully now. I wonder if I hit it at a time where the api was down but not publicly announced.
