### ISSUE TITLE
Unhandled Exception when trying to pull Ruinous Effigy

### ISSUE THREAD

**Issue by Mercer01** [TiredHobgoblin/Destiny-Collada-Generator#6]
https://www.light.gg/db/items/1363238943/ruinous-effigy/

Pulled "collectibleHash": 1392294260

Tool produces errors below

```
E:\Downloads\DestinyColladaGenerator-v1-4-0-Win64-Unpacked>DestinyColladaGenerator-v1-4-0.exe
Select an action:
[1] Convert local files
[2] Convert item from API
[3] Convert item from D1 API
[4] Quit
 > 2
Input item hash(es) > 1392294260
Output directory > E:\Downloads\D2Items
Calling item definition from manifest... Unhandled exception. System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at DestinyColladaGenerator.apiSupport.makeCallJson(String url)
   at DestinyColladaGenerator.apiSupport.convertByHash(String game)
   at DestinyColladaGenerator.Program.Main(String[] args)
```

**Comment by Mercer01** [comment]
I have now realised that this didn't work because it was unable to find the correct Hash.

Your choice but it may be a good idea to have better handling of incorrect Hashes/unable to find hash

**Comment by coasterreal** [comment]
Mercer, did you find the correct hash and if so, where did you find it at? I think the same thing is happening with On Ashen Wings
