### ISSUE TITLE
Unhandled Exception: On Ashen Wings

### ISSUE THREAD

**Issue by coasterreal** [TiredHobgoblin/Destiny-Collada-Generator#8]
This is probably really fresh but figured I would report it anyways.

Hash: 3170445301

Input item hash(es) > 3170445301
Output directory >
Calling item definition from manifest... Done.
Unhandled exception. System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'False'.
   at System.Text.Json.JsonDocument.TryGetNamedPropertyValue(Int32 index, ReadOnlySpan`1 propertyName, JsonElement& value)
   at System.Text.Json.JsonElement.TryGetProperty(ReadOnlySpan`1 propertyName, JsonElement& value)
   at System.Text.Json.JsonElement.TryGetProperty(String propertyName, JsonElement& value)
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at DestinyColladaGenerator.apiSupport.convertByHash(String game)
   at DestinyColladaGenerator.Program.Main(String[] args)

**Comment by TiredHobgoblin** [comment]
Issue appears to be due to the item being classified in the manifest the tool is currently using. I'm planning to add handling for that in the next release, as well as for incorrect hashes.

**Comment by coasterreal** [comment]
Ahhhh. Thanks for the reply! I'll keep checking for that update!
